workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        GRADLEW_PATH: "./gradlew"  # Gradle Wrapper 路径
    scripts:
      - echo "Starting build process..."
      - $GRADLEW_PATH clean         # 清理项目
      - $GRADLEW_PATH assembleDebug # 构建 Debug APK
    artifacts:
      - build/**/outputs/**/*.apk   # 保存生成的 APK 文件
