workflows:
  android-workflow:
    name: Build Android APK
    environment:
      vars:
        GRADLEW_PATH: "./gradlew"
    scripts:
      - echo "Starting build process..."
      - $GRADLEW_PATH clean         # 清理项目
      - $GRADLEW_PATH assembleRelease # 构建 Release 版本 APK
    artifacts:
      - build/**/outputs/**/*.apk   # 保存生成的 APK 文件
